import "./globals.css";
import Providers from "./providers";
import NavBar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";
import ThemeSwitcher from "@/components/themeSwitcher/themeSwitcher";

export const metadata = {
  title: "David Perez Tiburcio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <NavBar />
        <Providers>
          <ThemeSwitcher />
          {children}
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
