import NavBar from "../../components/navbar/NavBar";
import Footer from "../../components/footer/Footer";

export const metadata = {
  title: "David Perez Tiburcio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
